support subpath for volume mount

diff --git a/tests/test_yamls/pvc_volume_with_new.yaml b/tests/test_yamls/pvc_volume_with_new.yaml
--- a/tests/test_yamls/pvc_volume_with_new.yaml
+++ b/tests/test_yamls/pvc_volume_with_new.yaml
@@ -26,6 +26,7 @@ run: |
   df -h /mnt/data1 || (echo "df failed for data1" && exit 1)
   touch /mnt/data1/1.txt || (echo "touch failed for data1" && exit 1)
   ls -lart /mnt/data1 || (echo "ls failed for data1" && exit 1)
+  ls -lart /mnt/data1/subdir/path || (echo "ls failed for data1/subdir/path" && exit 1)
   # The following should fail since pvc1 won't be mounted
   if df -h /mnt/data3 2>/dev/null; then
     echo "ERROR: /mnt/data3 should not be mounted!" && exit 1
