update case

diff --git a/tests/test_yamls/pvc_volume.yaml b/tests/test_yamls/pvc_volume.yaml
--- a/tests/test_yamls/pvc_volume.yaml
+++ b/tests/test_yamls/pvc_volume.yaml
@@ -2,12 +2,12 @@ name: min
 resources:
   cpus: 0.1+
 volumes:
-  /mnt/data: pvc0
+  /mnt/data0: pvc0
 setup: |
   echo "running setup"
 
 run: |
   echo "check volume"
-  df -h /mnt/data0 || echo "df failed"
-  touch /mnt/data0/0.txt || echo "touch failed"
-  ls -lart /mnt/data0 || echo "ls failed"
+  df -h /mnt/data0 || (echo "df failed" && exit 1)
+  touch /mnt/data0/0.txt || (echo "touch failed" && exit 1)
+  ls -lart /mnt/data0 || (echo "ls failed" && exit 1)
