Fix concurrent SSH for Kubernetes

diff --git a/sky/templates/kubernetes-port-forward-proxy-command.sh.j2 b/sky/templates/kubernetes-port-forward-proxy-command.sh.j2
--- a/sky/templates/kubernetes-port-forward-proxy-command.sh.j2
+++ b/sky/templates/kubernetes-port-forward-proxy-command.sh.j2
@@ -13,29 +13,39 @@ if ! command -v lsof > /dev/null; then
   exit 1
 fi
 
-# Function to check if port is in use
-is_port_in_use() {
-    local port="$1"
-    lsof -i :${port} > /dev/null 2>&1
-}
+# Establishes connection between local port and the ssh jump pod
+KUBECTL_OUTPUT=$(mktemp)
+kubectl port-forward svc/{{ ssh_jump_name }} :22 > "${KUBECTL_OUTPUT}" 2>&1 &
 
-# Start from a fixed local port and increment if in use
-local_port={{ local_port }}
-while is_port_in_use "${local_port}"; do
-    local_port=$((local_port + 1))
+# Capture the PID for the backgrounded kubectl command
+K8S_PORT_FWD_PID=$!
+
+# Wait until kubectl port-forward is ready
+while ! grep -q "Forwarding from 127.0.0.1" "${KUBECTL_OUTPUT}"; do
+    sleep 0.1
 done
 
-# Establishes connection between local port and the ssh jump pod
-kubectl port-forward svc/{{ ssh_jump_name }} "${local_port}":22 &
+# Extract the local port number assigned by kubectl.
+# This is preferred over selecting a random port by ourself.
+# See - https://github.com/kubernetes/kubernetes/issues/74551#issuecomment-769185879
+local_port=$(awk -F: '/Forwarding from 127.0.0.1/{print $2}' "${KUBECTL_OUTPUT}" | awk -F' ' '{print $1}')
 
-# Terminate the port-forward process when this script exits.
+# Clean up the temporary file
+rm -f "${KUBECTL_OUTPUT}"
+
+# Add handler to terminate the port-forward process when this script exits.
 K8S_PORT_FWD_PID=$!
-trap "kill $K8S_PORT_FWD_PID" EXIT
+trap "[[ -e /proc/$K8S_PORT_FWD_PID ]] && kill $K8S_PORT_FWD_PID" EXIT
 
-# checks if a connection to local_port of 127.0.0.1:[local_port] is established
+# Checks if a connection to local_port of 127.0.0.1:[local_port] is established
 while ! nc -z 127.0.0.1 "${local_port}"; do
     sleep 0.1
 done
+
+# To avoid errors when many concurrent requests are sent (see https://github.com/skypilot-org/skypilot/issues/2628),
+# we add a random delay before establishing the socat connection.
+# Empirically, this needs to be at least 1 second. We set this to be random between 1 and 2 seconds.
+sleep $(shuf -i 10-20 -n 1 | awk '{printf "%f", $1/10}')
 
 # Establishes two directional byte streams to handle stdin/stdout between
 # terminal and the jump pod.
