Address exec permission issue
Signed-off-by: Aylei <rayingecho@gmail.com>

diff --git a/sky/templates/kubernetes-ray.yml.j2 b/sky/templates/kubernetes-ray.yml.j2
--- a/sky/templates/kubernetes-ray.yml.j2
+++ b/sky/templates/kubernetes-ray.yml.j2
@@ -505,6 +505,11 @@ available_node_types:
                     done
                 }
                 wait_for_fusermount
+                # Some distributions may might hostPath with noexec, copy the binary in this case.
+                if ! fusermount -V; then
+                    echo "fusermount -V failed, copying fusermount-shim directly"
+                    $(prefix_cmd) cp -p {{k8s_fusermount_shared_dir}}/fusermount-shim "$FUSERMOUNT_PATH"
+                fi
                 )
               ) &
               {% endif %}
