Add dropbear SSH support for containers

diff --git a/sky/templates/slurm-ray.yml.j2 b/sky/templates/slurm-ray.yml.j2
--- a/sky/templates/slurm-ray.yml.j2
+++ b/sky/templates/slurm-ray.yml.j2
@@ -69,22 +69,27 @@ initialization_commands: []
 #
 # Increment the following for catching performance bugs easier:
 #   current num items (num SSH connections): 1
+{% set user = 'root' if image_id is not none else ssh_user %}
 setup_commands:
   - |
     {%- for initial_setup_command in initial_setup_commands %}
     {{ initial_setup_command }}
     {%- endfor %}
+    # TODO(kevin): Do this only for non-container jobs.
+    # Also, for containers, modify ~/.sky_ssh_rc to make it work.
+    # Currently, ssh will take you to your user's home directory, not
+    # the container user's (always `root` in our case, for now) home directory.
     # Generate host key for sshd -i if not exists
-    mkdir -p ~{{ssh_user}}/.ssh && chmod 700 ~{{ssh_user}}/.ssh
-    [ -f ~{{ssh_user}}/.ssh/{{slurm_sshd_host_key_filename}} ] || ssh-keygen -t ed25519 -f ~{{ssh_user}}/.ssh/{{slurm_sshd_host_key_filename}} -N "" -q
+    mkdir -p ~{{user}}/.ssh && chmod 700 ~{{user}}/.ssh
+    [ -f ~{{user}}/.ssh/{{slurm_sshd_host_key_filename}} ] || ssh-keygen -t ed25519 -f ~{{user}}/.ssh/{{slurm_sshd_host_key_filename}} -N "" -q
     # Add public key to user's authorized_keys if not already present
-    grep -qF 'skypilot:ssh_public_key_content' ~{{ssh_user}}/.ssh/authorized_keys 2>/dev/null || cat >> ~{{ssh_user}}/.ssh/authorized_keys <<'SKYPILOT_SSH_KEY_EOF'
+    grep -qF 'skypilot:ssh_public_key_content' ~{{user}}/.ssh/authorized_keys 2>/dev/null || cat >> ~{{user}}/.ssh/authorized_keys <<'SKYPILOT_SSH_KEY_EOF'
     skypilot:ssh_public_key_content
     SKYPILOT_SSH_KEY_EOF
-    chmod 600 ~{{ssh_user}}/.ssh/authorized_keys
+    chmod 600 ~{{user}}/.ssh/authorized_keys
 
-    mkdir -p ~{{ssh_user}}/.sky
-    cat > ~{{ssh_user}}/.sky_ssh_rc <<'SKYPILOT_SSH_RC'
+    mkdir -p ~{{user}}/.sky
+    cat > ~{{user}}/.sky_ssh_rc <<'SKYPILOT_SSH_RC'
     # Added by SkyPilot: override HOME for Slurm interactive sessions
     if [ -n "${{slurm_cluster_name_env_var}}" ]; then
         CLUSTER_DIR=~/.sky_clusters/${{slurm_cluster_name_env_var}}
@@ -94,12 +99,59 @@ setup_commands:
         fi
     fi
     SKYPILOT_SSH_RC
-    grep -q "source ~/.sky_ssh_rc" ~{{ssh_user}}/.bashrc 2>/dev/null || (echo "" >> ~{{ssh_user}}/.bashrc && echo "source ~/.sky_ssh_rc" >> ~{{ssh_user}}/.bashrc)
+    grep -q "source ~/.sky_ssh_rc" ~{{user}}/.bashrc 2>/dev/null || (echo "" >> ~{{user}}/.bashrc && echo "source ~/.sky_ssh_rc" >> ~{{user}}/.bashrc)
     {{ setup_sky_dirs_commands }}
     {{ conda_installation_commands }}
     {{ uv_installation_commands }}
     {{ skypilot_wheel_installation_commands }}
     {{ copy_skypilot_templates_commands }}
+{% if image_id is not none %}
+    # Install dropbear and socat for container SSH.
+    # OpenSSH fails in enroot containers created with --container-remap-root with:
+    #   "permanently_set_uid: was able to restore old [e]gid [preauth]"
+    # sshd verifies it can actually drop privileges, which doesn't work with
+    # --container-remap-root because of the uid remapping.
+    # See:
+    # - https://github.com/NVIDIA/pyxis/issues/85#issuecomment-1201913582
+    # - https://github.com/NVIDIA/enroot/issues/92
+    #
+    # So we use Dropbear (https://matt.ucc.asn.au/dropbear/dropbear.html), a
+    # lightweight SSH server popular in embedded and resource-constrained
+    # environments. It's actively maintained (https://github.com/mkj/dropbear/releases)
+    # and doesn't have the same issue with OpenSSH.
+    #
+    # This runs on both host and container; only install when root (container).
+    # TODO(kevin): Mount a ccache dir from the host to speed up dropbear builds.
+    if [ "$(id -u)" = "0" ]; then
+      set -e
+      DROPBEAR_VERSION=2025.89
+      PACKAGES="socat iproute2"
+      if ! /usr/local/bin/dropbear -V 2>&1 | grep -q "$DROPBEAR_VERSION"; then
+        cd /tmp
+        if command -v apt-get >/dev/null 2>&1; then
+          export DEBIAN_FRONTEND=noninteractive
+          apt-get update -y >/dev/null
+          apt-get install -y build-essential $PACKAGES >/dev/null
+        elif command -v yum >/dev/null 2>&1; then
+          yum makecache >/dev/null
+          yum install -y gcc make $PACKAGES >/dev/null
+        elif command -v dnf >/dev/null 2>&1; then
+          dnf makecache >/dev/null
+          dnf install -y gcc make $PACKAGES >/dev/null
+        elif command -v apk >/dev/null 2>&1; then
+          apk update >/dev/null
+          apk add --no-cache build-base $PACKAGES >/dev/null
+        fi
+        curl -sL https://matt.ucc.asn.au/dropbear/releases/dropbear-$DROPBEAR_VERSION.tar.bz2 | tar xj
+        cd dropbear-$DROPBEAR_VERSION
+        ./configure --disable-zlib --disable-syslog --disable-wtmp --disable-lastlog >/dev/null
+        make -j$(nproc) PROGRAMS="dropbear" >/dev/null
+        cp dropbear /usr/local/bin/
+        cd /; rm -rf /tmp/dropbear-$DROPBEAR_VERSION
+      fi
+      mkdir -p /etc/dropbear
+    fi
+{% endif %}
 
 head_node: {}
 worker_nodes: {}
