test

diff --git a/.github/workflows/pypi-nightly-build.yml b/.github/workflows/pypi-nightly-build.yml
--- a/.github/workflows/pypi-nightly-build.yml
+++ b/.github/workflows/pypi-nightly-build.yml
@@ -79,17 +79,17 @@ jobs:
           path: dist/
 
       # Trigger Buildkite smoke tests
-      - name: Trigger Buildkite Smoke Tests
-        id: trigger_buildkite
-        uses: buildkite/trigger-pipeline-action@v2.3.0
-        with:
-          buildkite_api_access_token: ${{ secrets.BUILDKITE_TOKEN }}
-          pipeline: "skypilot-1/smoke-tests"
-          branch: "master"
-          commit: "${{ github.sha }}"
-          message: "nightly-build-pypi"
-          ignore_pipeline_branch_filter: true
-          build_env_vars: '{"ARGS": "--aws"}'
+      # - name: Trigger Buildkite Smoke Tests
+      #   id: trigger_buildkite
+      #   uses: buildkite/trigger-pipeline-action@v2.3.0
+      #   with:
+      #     buildkite_api_access_token: ${{ secrets.BUILDKITE_TOKEN }}
+      #     pipeline: "skypilot-1/smoke-tests"
+      #     branch: "master"
+      #     commit: "${{ github.sha }}"
+      #     message: "nightly-build-pypi"
+      #     ignore_pipeline_branch_filter: true
+      #     build_env_vars: '{"ARGS": "--aws"}'
 
   extract-build-number:
     needs: nightly-build-pypi
@@ -97,20 +97,21 @@ jobs:
     with:
       json_data: ${{ needs.nightly-build-pypi.outputs.buildkite_json }}
 
-  wait-for-buildkite:
-    needs: extract-build-number
-    uses: ./.github/workflows/wait-for-buildkite.yml
-    with:
-      organization: "skypilot-1"
-      pipeline: "smoke-tests"
-      build_number: ${{ needs.extract-build-number.outputs.build_number }}
-      timeout_minutes: 120
-    secrets:
-      BUILDKITE_TOKEN: ${{ secrets.BUILDKITE_TOKEN }}
+  # wait-for-buildkite:
+  #   needs: extract-build-number
+  #   uses: ./.github/workflows/wait-for-buildkite.yml
+  #   with:
+  #     organization: "skypilot-1"
+  #     pipeline: "smoke-tests"
+  #     build_number: ${{ needs.extract-build-number.outputs.build_number }}
+  #     timeout_minutes: 120
+  #   secrets:
+  #     BUILDKITE_TOKEN: ${{ secrets.BUILDKITE_TOKEN }}
 
   publish-to-pypi:
-    needs: [nightly-build-pypi, wait-for-buildkite]
-    if: needs.wait-for-buildkite.outputs.build_status == 'success'
+    needs: [nightly-build-pypi]
+    # needs: [nightly-build-pypi, wait-for-buildkite]
+    # if: needs.wait-for-buildkite.outputs.build_status == 'success'
     runs-on: ubuntu-latest
     steps:
       - name: Download distribution artifacts
@@ -119,12 +120,12 @@ jobs:
           name: python-package-distributions
           path: dist/
 
-      - name: Publish distribution to Test PyPI
-        uses: pypa/gh-action-pypi-publish@release/v1
-        with:
-          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
-          repository-url: https://test.pypi.org/legacy/
-          skip-existing: true
+      # - name: Publish distribution to Test PyPI
+      #   uses: pypa/gh-action-pypi-publish@release/v1
+      #   with:
+      #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
+      #     repository-url: https://test.pypi.org/legacy/
+      #     skip-existing: true
 
       - name: Validate published package
         run: |
@@ -139,7 +140,7 @@ jobs:
           sky -c
           sky check
           sky show-gpus
-          sky dashboard
+          sky dashboard || echo "launch dashboard failed"
           # Verify dashboard endpoint is accessible
           curl --fail --silent --show-error --output /dev/null http://127.0.0.1:46580/dashboard/ || echo "Dashboard endpoint is not accessible" && exit 1
           # Verify version
@@ -152,50 +153,50 @@ jobs:
           fi
           echo "Version verified successfully!"
 
-      - name: Publish distribution to PyPI
-        uses: pypa/gh-action-pypi-publish@release/v1
-        with:
-          password: ${{ secrets.PYPI_API_TOKEN }}
-          skip-existing: true
+      # - name: Publish distribution to PyPI
+      #   uses: pypa/gh-action-pypi-publish@release/v1
+      #   with:
+      #     password: ${{ secrets.PYPI_API_TOKEN }}
+      #     skip-existing: true
 
-  notify-slack-failure:
-    runs-on: ubuntu-latest
-    needs: [check-date, nightly-build-pypi, extract-build-number, wait-for-buildkite, publish-to-pypi]
-    if: failure() # Only run this job if any of the previous jobs failed
-    steps:
-      - name: Prepare failure message
-        id: message_content
-        run: |
-          TITLE_TEXT="Workflow ${{ github.workflow }} failed."
-          COMMIT_SHA="${{ github.sha }}"
-          COMMIT_URL="${{ github.server_url }}/${{ github.repository }}/commit/${COMMIT_SHA}"
-          SHORT_SHA=$(echo "$COMMIT_SHA" | cut -c1-7)
-          if [[ "${{ needs.wait-for-buildkite.result }}" == "failure" ]]; then
-            MARKDOWN_TEXT="🚨 Workflow <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|*${{ github.workflow }}*> failed at Buildkite step for commit <${COMMIT_URL}|${SHORT_SHA}>. <https://buildkite.com/skypilot-1/smoke-tests/builds/${{ needs.extract-build-number.outputs.build_number }}|Buildkite Log>"
-            echo "message_text=${TITLE_TEXT}" >> $GITHUB_OUTPUT
-            echo "message_block=${MARKDOWN_TEXT}" >> $GITHUB_OUTPUT
-          else
-            MARKDOWN_TEXT="🚨 Workflow <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|*${{ github.workflow }}*> failed for commit <${COMMIT_URL}|${SHORT_SHA}>."
-            echo "message_text=${TITLE_TEXT}" >> $GITHUB_OUTPUT
-            echo "message_block=${MARKDOWN_TEXT}" >> $GITHUB_OUTPUT
-          fi
+  # notify-slack-failure:
+  #   runs-on: ubuntu-latest
+  #   needs: [check-date, nightly-build-pypi, extract-build-number, wait-for-buildkite, publish-to-pypi]
+  #   if: failure() # Only run this job if any of the previous jobs failed
+  #   steps:
+  #     - name: Prepare failure message
+  #       id: message_content
+  #       run: |
+  #         TITLE_TEXT="Workflow ${{ github.workflow }} failed."
+  #         COMMIT_SHA="${{ github.sha }}"
+  #         COMMIT_URL="${{ github.server_url }}/${{ github.repository }}/commit/${COMMIT_SHA}"
+  #         SHORT_SHA=$(echo "$COMMIT_SHA" | cut -c1-7)
+  #         if [[ "${{ needs.wait-for-buildkite.result }}" == "failure" ]]; then
+  #           MARKDOWN_TEXT="🚨 Workflow <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|*${{ github.workflow }}*> failed at Buildkite step for commit <${COMMIT_URL}|${SHORT_SHA}>. <https://buildkite.com/skypilot-1/smoke-tests/builds/${{ needs.extract-build-number.outputs.build_number }}|Buildkite Log>"
+  #           echo "message_text=${TITLE_TEXT}" >> $GITHUB_OUTPUT
+  #           echo "message_block=${MARKDOWN_TEXT}" >> $GITHUB_OUTPUT
+  #         else
+  #           MARKDOWN_TEXT="🚨 Workflow <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|*${{ github.workflow }}*> failed for commit <${COMMIT_URL}|${SHORT_SHA}>."
+  #           echo "message_text=${TITLE_TEXT}" >> $GITHUB_OUTPUT
+  #           echo "message_block=${MARKDOWN_TEXT}" >> $GITHUB_OUTPUT
+  #         fi
 
-      - name: Notify Slack channel on failure
-        uses: slackapi/slack-github-action@v2.0.0
-        with:
-          method: chat.postMessage
-          token: ${{ secrets.SLACK_BOT_TOKEN }}
-          payload: |
-            {
-              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
-              "text": "${{ steps.message_content.outputs.message_text }}",
-              "blocks": [
-                {
-                  "type": "section",
-                  "text": {
-                    "type": "mrkdwn",
-                    "text": "${{ steps.message_content.outputs.message_block }}"
-                  }
-                }
-              ]
-            }
+  #     - name: Notify Slack channel on failure
+  #       uses: slackapi/slack-github-action@v2.0.0
+  #       with:
+  #         method: chat.postMessage
+  #         token: ${{ secrets.SLACK_BOT_TOKEN }}
+  #         payload: |
+  #           {
+  #             "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
+  #             "text": "${{ steps.message_content.outputs.message_text }}",
+  #             "blocks": [
+  #               {
+  #                 "type": "section",
+  #                 "text": {
+  #                   "type": "mrkdwn",
+  #                   "text": "${{ steps.message_content.outputs.message_block }}"
+  #                 }
+  #               }
+  #             ]
+  #           }
